### ISSUE TITLE
Will not compile Ruby gems correctly without libmysqlclient-dev

### ISSUE THREAD

**Issue by flybd5** [sinfomicien/mysql2_chef_gem#21] opened 2016-09-06 06:56 UTC
I tried to use this cookbook as a dependency on the WordPress cookbook on Ubuntu 14.04, a clean install, properly apt-get updated and upgraded. The cookbook fails when it is trying to compile Ruby gems related to mysql. (Sorry, I am not a Ruby expert, just a devops admin). The solution was to "apt-get install libmysqlclient-dev". I would add this to the code but I have no idea where to put it and how to specify the dependency on Ubuntu 14.04.

**Comment by acoulton** [comment] 2016-09-07 14:27
I've also run into this, it appears to be caused by chef-cookbooks/mysql#457 - the mysql_client resource no longer installs the dev libraries.

**Comment by jpmat296** [comment] 2016-12-02 09:59
Both issue #21 #22 are fixed by my PR chef-cookbooks/mysql#492.

**Comment by tas50** [comment] 2017-03-29 07:09
This is fixed in mysql which the latest cookbook depends on. Give the new cookbook a try.

**Closed by tas50** 2017-03-29 07:09 UTC
