### ISSUE TITLE
Deprecated feature to be aware for upcoming Chef 13

### ISSUE THREAD

**Issue by AneudyM** [sinfomicien/mysql2_chef_gem#18] opened 2016-08-22 06:17 UTC
```
Deprecated features used!
  nil is an invalid value for version of resource . 
In Chef 13, this warning will change to an error. Error: Property version must be one of: String!  
You passed nil. at 1 location:
    - /var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:17:in `block (2 levels) in <class:Mysql>'
```

**Comment by Restless-ET** [comment] 2016-08-30 09:20
Possible duplicate of #8.

**Comment by benquike** [comment] 2016-11-08 01:05
is it solved?

**Comment by frezbo** [comment] 2017-02-18 15:08
@benquike solved in my fork

**Comment by tas50** [comment] 2017-03-14 16:09
This has been resolved on master

**Closed by tas50** 2017-03-14 16:09 UTC

**Comment by frezbo** [comment] 2017-03-15 02:33
@tas50 When can we expect a new release?
